FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /root

# install ORBSLAM3 ROS package

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils    
    
RUN apt-get update && apt-get install -y libtbb-dev \
    libyaml-cpp-dev software-properties-common \
    git build-essential \
    cmake libeigen3-dev \
    python3-pip \
    libopencv-contrib-dev \
    libopencv-dev \
    gdb \
    zlib1g-dev


RUN apt-get install -y unzip pkg-config autoconf \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    # Use libvtk5-dev, libgtk2.0-dev in ubuntu 16.04 \
    libvtk7-dev libgtk-3-dev

RUN apt-get install -y libcanberra-gtk-module libcanberra-gtk3-module \
    libatlas-base-dev gfortran \
    libparmetis-dev \
    python3-wstool
    # libtbb recommended for speed: \

RUN python3 -m pip install evo


RUN apt-get update && apt-get install -y libsuitesparse-dev

RUN git clone https://github.com/borglab/gtsam.git && \
    cd gtsam && \
    git checkout 4.2a6       && \   
    mkdir build && cd build && \
    cmake -DGTSAM_POSE3_EXPMAP=ON -DGTSAM_ROT3_EXPMAP=ON -DGTSAM_USE_SYSTEM_EIGEN=ON -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF .. && \
    make -j && make install

RUN apt-get update && apt-get install -y libgl1-mesa-dev libglew-dev libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols


RUN git clone https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    git checkout v0.6 && \
    mkdir build && cd build && cmake .. -DBUILD_PANGOLIN_GL=ON -DBUILD_PANGOLIN_GLEW=ON && make -j8 && make install

